### ISSUE TITLE
Cant place shulker box in the backpack

### ISSUE THREAD

**Issue by ShinyRayquaza9923** [Flanks255/simplybackpacks#19]
**Describe the bug**
X. I cannot craft any of the backpack. I checked the recipe from the CurseForge (because I didn't put JEI) so many times and still doesn't work. I was using vanilla crafting table.
    I found the problem. It's not bone meal and lapis, it's white dye and blue dye......
2. The shulker box that I haven't placed down can go in the backpack but after putting it on the ground then picking it up I can no longer place it in the backpack. Is this intentional feature?

Just curious, why don't you have comment section in the curse forge?

Please provide the version of forge used, and the mod version.
- Forge 31.1.48
- Mod Version 1.15.2 - 1.4.5

**Comment by Flanks255** [comment]
so the 1.15 recipe may be slightly different, since mojang separated dyes from items.
so it may be white dye in place of bone meal.

as far as placing the shulker box inside, this is intentional, the backpacks do not allow items that hold other items inside of themselves inside, it is dangerous to allow them inside as you can corrupt your world if you do it too much.

as far as curseforge comments, while i did leave them on when i first started making mods, i quickly turned them off, as people started using it for bugs and problems, instead of a github issue, github works much better for tracking and closing problems.

**Comment by ShinyRayquaza9923** [comment]
Thank you for replying and I understand :D

**Comment by ShinyRayquaza9923** [comment]
I'm not sure if you can still read this since this is a closed issue but I just crashed my game by placing a backpack in a shulker box, picked it up, and hover the mouse over it. As you said you intentionally do not allow placing of items that holds other items in the backpack, I think you should also do the same with shulker box? I don't know.

Simply put, I think you should disallow backpack going into shulker box just like the vice versa.

**Comment by Flanks255** [comment]
sadly i have no control over how shulkers work, does it happen every time?

**Comment by ShinyRayquaza9923** [comment]
i didnt try more than once since it was in my survival world and i dont want to break it. Maybe i can try in test world. But if you dont have control, i will just be careful. :)

I just tried it and i think it crashes always.

**Comment by Flanks255** [comment]
hmmm, what pack is this in, do you know what all items are in the backpack, and the shulker? id like to test it a bit, im wondering if its a full nbt overload, or if another mod is trying to parse the contents of the shulker and exploding...

**Comment by ShinyRayquaza9923** [comment]
I just use bunch of mods that I like. I don't know if that's called pack.
I think during my tests I didn't have any items in the backpack nor shulker.
1 mod that might affect is shulker tooltips by ZephaniahNoah but it's just my guess.
Is there a way to send png file here? I wanted to send screenshot of the mods I'm using but I don't know how.
